version: '3.8'

services:
  micro-template:
    container_name: test-container
    image: micro-template
    build:
      context: .
      args:
        - HOST_PORT=5000
        - PM2_FILE=pm2-prod.json
    environment:
      - PM2_FILE=pm2-prod.json
      - NODE_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
