name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        # Add your deployment steps here
        echo "Deployment steps"
        
        # Use sshpass to provide the password
        sshpass -p ${{ secrets.SERVER_OVMS_PASSWORD }} ssh ovms@192.168.30.41 "cd /app/deployment && less ovms-be-deployment.yaml"
