name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - '*'
  workflow_dispatch:
    inputs:
      custom-tag:
        description: 'Custom tag for the Docker image'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PM2_FILE: pm2-prod.json
      HOST_PORT: 5000
      GITHUB_REGISTRY: ghcr.io

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Image Tag
      run: echo "IMAGE_TAG=${{ github.event.inputs.custom-tag || (echo $GITHUB_REF | awk -F/ '{print $NF}') }}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.GITHUB_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_TOKEN }}

    - name: Show Docker images before build
      run: docker images

    - name: Build the Docker image
      run: docker build --build-arg PM2_FILE=${{ env.PM2_FILE }} --build-arg HOST_PORT=${{ env.HOST_PORT }} -t ${{ env.GITHUB_REGISTRY }}/tanyawitentro/micro-template:${IMAGE_TAG} .

    - name: Show Docker images after build
      run: docker images

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ${{ env.GITHUB_REGISTRY }}/tanyawitentro/micro-template:${IMAGE_TAG}
