name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAG_NAME: v2.0
      PM2_FILE: pm2-prod.json
      HOST_PORT: 5000
      CR_TOKEN: ${{ secrets.CR_TOKEN }}
      REGISTRY: ghcr.io

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          echo "Building Docker Image..."
          docker buildx build \
            --build-arg PM2_FILE=${PM2_FILE} \
            --build-arg HOST_PORT=${HOST_PORT} \
            -t "${{ github.repository_owner }}/micro-template:${TAG_NAME}" \
            .

      - name: Login to GitHub Container Registry
        run: echo $CR_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker Image to GitHub Container Registry
        run: docker push "${REGISTRY}/${{ github.repository_owner }}/micro-template:${TAG_NAME}"

      - name: Print Docker Image Name
        run: echo "Docker image ${GITHUB_REPOSITORY}/micro-template:${TAG_NAME}"
