name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAG_NAME: v1.0
      PM2_FILE: pm2-prod.json
      HOST_PORT: 5000
      REGISTRY: ghcr.io

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          echo "Building Docker Image..."
          docker buildx build \
            -t "micro-template:${TAG_NAME}" \
            .
          docker images  # Print Docker images after the build
