name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Set default values for environment variables
      TAG_NAME: v2.0
      PM2_FILE: pm2-prod.json
      HOST_PORT: 5000

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker buildx build \
            --build-arg PM2_FILE=${PM2_FILE} \
            --build-arg HOST_PORT=${HOST_PORT} \
            -t micro-template:${TAG_NAME} \
            .
          
      - name: Tag Docker Image
        run: |
          docker tag micro-template:${TAG_NAME} tanyawitentro/micro-template:${TAG_NAME}

      - name: Push Docker Image to Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push tanyawitentro/micro-template:${TAG_NAME}

        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
