name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PM2_FILE: pm2-prod.json
      HOST_PORT: 5000

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_TOKEN }}

    - name: Show Docker images before build
      run: docker images

    - name: Build the Docker image
      run: docker build --build-arg PM2_FILE=${{ env.PM2_FILE }} --build-arg HOST_PORT=${{ env.HOST_PORT }} -t ghcr.io/tanyawitentro/micro-template:latest .

    - name: Show Docker images after build
      run: docker images

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/tanyawitentro/micro-template:latest
