name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAG_NAME: v2.0
      PM2_FILE: pm2-prod.json
      HOST_PORT: 5000

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          echo "Building Docker Image..."
          docker buildx build \
            --build-arg PM2_FILE=${PM2_FILE} \
            --build-arg HOST_PORT=${HOST_PORT} \
            -t micro-template:${TAG_NAME} \
            .

      # You can add more steps here, but no need to push the image.

      - name: Print Docker Image Name
        run: echo "Docker image micro-template:${TAG_NAME}"
